### ISSUE TITLE
can't open file '/code/dockerize-me/dockerize.py'

### ISSUE THREAD

**Issue by fwilhe** [fiunchinho/dockerize-me#1]
I found this tool via the devops weekly newsletter and like the idea.

When I try to run the command as described in the readme, the following happens:

```
$ docker run -it --rm -v $PWD:/code fiunchinho/dockerize-me                 
python: can't open file '/code/dockerize-me/dockerize.py': [Errno 2] No such file or directory
```

When I start `sh` in the container, `/code` looks odd:

```
/ # ls -la /code
ls: can't open '/code': Permission denied
total 0
/ # ls -la / | grep code
drwx------   82 1000     1000          4096 May 29 14:53 code
```

Not sure what's wrong. Could you take a look at this?

**Comment by fiunchinho** [comment]
Hey! I think you found a bug. I just pushed a potential solution, and the image is being built on DockerHub. Can you try again?

Thank you for your feedback

**Comment by fwilhe** [comment]
Works after pulling again from the docker hub. Thanks!
